/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class MenuUtamaMahasiswa extends javax.swing.JFrame {
    
    private void loadStatusKrsDashboard() {
        try {
            Database db = new Database();
            
            // 1. Cari tahu dulu periode mana yang sedang aktif (Buka)
            String idPeriodeAktif = "";
            java.sql.ResultSet rsPeriode = db.readDBSafe("SELECT id_periode FROM periode WHERE status_krs = 'Buka' LIMIT 1");
            if (rsPeriode != null && rsPeriode.next()) {
                idPeriodeAktif = rsPeriode.getString("id_periode");
            }

            // 2. Jika ada periode aktif, cari KRS mahasiswa tersebut
            if (!idPeriodeAktif.isEmpty()) {
                String sql = "SELECT status_validasi FROM krs_header WHERE nim = ? AND id_periode = ?";
                java.sql.ResultSet rsStatus = db.readDBSafe(sql, Login.getUserLogin(), idPeriodeAktif);
                
                if (rsStatus != null && rsStatus.next()) {
                    String status = rsStatus.getString("status_validasi");
                    lblStatusKrs.setText("Status KRS Anda Saat Ini: " + status.toUpperCase());
                    
                    // Mainkan warna agar UI terlihat lebih hidup dan profesional
                    if (status.equals("Disetujui")) {
                        lblStatusKrs.setForeground(new java.awt.Color(0, 153, 0)); // Warna Hijau Tua
                    } else if (status.equals("Ditolak")) {
                        lblStatusKrs.setForeground(java.awt.Color.RED); // Warna Merah
                    } else {
                        lblStatusKrs.setForeground(new java.awt.Color(204, 102, 0)); // Warna Oranye/Kuning
                    }
                } else {
                    lblStatusKrs.setText("Status KRS Anda Saat Ini: BELUM MENGAJUKAN");
                    lblStatusKrs.setForeground(java.awt.Color.BLACK);
                }
            } else {
                lblStatusKrs.setText("Status KRS: Tidak Ada Periode KRS yang Terbuka");
                lblStatusKrs.setForeground(java.awt.Color.GRAY);
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat status KRS di Beranda: " + e.getMessage());
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtamaMahasiswa.class.getName());

    /**
     * Creates new form MenuUtamaMahasiswa
     */
    public MenuUtamaMahasiswa() {
        initComponents();
        loadStatusKrsDashboard();
         WindowUtil.setWindow80PercentCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKontenMhs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIsiKrs = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        lblStatusKrs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKontenMhs.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Dashboard Mahasiswa - Sistem Akademik");

        jLabel2.setText("Siakad");

        btnIsiKrs.setText("Isi KRS");
        btnIsiKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsiKrsActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnJadwal.setText("Jadwal");
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addComponent(btnIsiKrs, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(btnLogout)
                    .addComponent(btnJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnIsiKrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        lblStatusKrs.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelKontenMhs, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatusKrs)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(264, 264, 264)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusKrs)
                        .addGap(3, 3, 3)
                        .addComponent(panelKontenMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(499, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIsiKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsiKrsActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan wadah konten utama dari panel lain yang sedang aktif
        panelKontenMhs.removeAll();
        
        // 2. Buat objek dari PanelIsiKRS yang berisi logika transaksi
        PanelIsiKRS pKrs = new PanelIsiKRS();
        
        // 3. Masukkan PanelIsiKRS ke dalam wadah dengan posisi CENTER (BorderLayout)
        panelKontenMhs.add(pKrs, java.awt.BorderLayout.CENTER);
        
        // 4. Paksa Java Swing untuk merender ulang tampilan secara real-time
        panelKontenMhs.repaint();
        panelKontenMhs.revalidate();
    }//GEN-LAST:event_btnIsiKrsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // 1. Munculkan pop-up konfirmasi
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            
            // ---> BERSIHKAN SESI SEBELUM LOGOUT <---
            Login.clearSession(); 
            
            this.dispose(); // Tutup menu utama
            new Login().setVisible(true); // Buka kembali layar login
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        panelKontenMhs.removeAll();
        panelKontenMhs.add(new PanelJadwalMahasiswa());
        panelKontenMhs.repaint();
        panelKontenMhs.revalidate();
    }//GEN-LAST:event_btnJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtamaMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIsiKrs;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblStatusKrs;
    private javax.swing.JPanel panelKontenMhs;
    // End of variables declaration//GEN-END:variables
}
