/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class MenuUtamaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtamaAdmin.class.getName());

    /**
     * Creates new form MenuUtamaAdmin
     */
    public MenuUtamaAdmin() {   
        initComponents();
        panelKonten.removeAll(); 
        panelKonten.add(new PanelDashboard()); 
        panelKonten.repaint(); 
        panelKonten.revalidate();
        WindowUtil.setWindow80PercentCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProdi = new javax.swing.JButton();
        btnMatkul = new javax.swing.JButton();
        btnDosen = new javax.swing.JButton();
        btnMhs = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAkun = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        btnPeriode = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProdi.setText("Data Prodi");
        btnProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdiActionPerformed(evt);
            }
        });

        btnMatkul.setText("Data Mata Kuliah");
        btnMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatkulActionPerformed(evt);
            }
        });

        btnDosen.setText("Data Dosen");
        btnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosenActionPerformed(evt);
            }
        });

        btnMhs.setText("Data Mahasiswa");
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAkun.setText("Data Akun");
        btnAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkunActionPerformed(evt);
            }
        });

        btnKelas.setText("Data Kelas");
        btnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelasActionPerformed(evt);
            }
        });

        btnPeriode.setText("Periode");
        btnPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodeActionPerformed(evt);
            }
        });

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAkun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLogout)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatkul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAkun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeriode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        jLabel1.setText("Dashboard Admin - Sistem Akademik");

        jLabel2.setText("Siakad");

        panelKonten.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdiActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan panel agar tidak bertumpuk
        panelKonten.removeAll();

        // 2. Buat objek panel baru
        PanelProdi prodi = new PanelProdi();

        // 3. Tambahkan ke panelKonten dengan posisi CENTER agar memenuhi layar
        panelKonten.add(prodi, java.awt.BorderLayout.CENTER);

        // 4. WAJIB: Refresh UI agar perubahan terlihat
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnProdiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // 1. Munculkan pop-up konfirmasi
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            
            // ---> BERSIHKAN SESI SEBELUM LOGOUT <---
            Login.clearSession(); 
            
            this.dispose(); // Tutup menu utama
            new Login().setVisible(true); // Buka kembali layar login
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkulActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan area panel kanan dari halaman sebelumnya (misal dari halaman Prodi)
        panelKonten.removeAll();
        
        // 2. Buat objek dari halaman PanelMatkul
        PanelMatkul matkul = new PanelMatkul();
        
        // 3. Masukkan halaman Matkul ke panel kanan dengan posisi memenuhi layar (CENTER)
        panelKonten.add(matkul, java.awt.BorderLayout.CENTER);
        
        // 4. Refresh tampilan agar perubahannya langsung muncul
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnMatkulActionPerformed

    private void btnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosenActionPerformed
        // TODO add your handling code here:
        // 1. Bersihkan panel kanan
        panelKonten.removeAll();
        
        // 2. Panggil PanelDosen
        PanelDosen dosen = new PanelDosen();
        
        // 3. Masukkan ke wadah dengan posisi Center agar melar otomatis
        panelKonten.add(dosen, java.awt.BorderLayout.CENTER);
        
        // 4. Refresh tampilan
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnDosenActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        PanelMahasiswa mhs = new PanelMahasiswa();
        panelKonten.add(mhs, java.awt.BorderLayout.CENTER);
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkunActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        PanelAkun akun = new PanelAkun();
        panelKonten.add(akun, java.awt.BorderLayout.CENTER);
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnAkunActionPerformed

    private void btnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelasActionPerformed
        // TODO add your handling code here:
                panelKonten.removeAll();
        PanelKelas akun = new PanelKelas();
        panelKonten.add(akun, java.awt.BorderLayout.CENTER);
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnKelasActionPerformed

    private void btnPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodeActionPerformed
        // TODO add your handling code here:
        // 1. Kosongkan area tengah (Panel Utama) tempat panel biasa muncul
    panelKonten.removeAll(); 

    // 2. Panggil PanelPeriode yang baru saja kamu buat
    PanelPeriode pPeriode = new PanelPeriode();

    // 3. Atur ukurannya agar pas dengan panel konten
    pPeriode.setSize(panelKonten.getSize());

    // 4. Masukkan ke panel konten dan refresh layarnya
    panelKonten.add(pPeriode);
    panelKonten.repaint();
    panelKonten.revalidate();
    }//GEN-LAST:event_btnPeriodeActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // 1. Bersihkan panel lama
        panelKonten.removeAll();
        
        // 2. Buat objek panel laporan
        PanelLaporan laporan = new PanelLaporan();
        
        // 3. Masukkan ke panelKonten dan paksa letakkan di TENGAH (Penuhi layar)
        panelKonten.add(laporan, java.awt.BorderLayout.CENTER);
        
        // 4. Hitung dan gambar ulang layarnya
        panelKonten.revalidate();
        panelKonten.repaint();
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtamaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnDosen;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMatkul;
    private javax.swing.JButton btnMhs;
    private javax.swing.JButton btnPeriode;
    private javax.swing.JButton btnProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKonten;
    // End of variables declaration//GEN-END:variables
}
