/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class PanelAkun extends javax.swing.JPanel {
private String idAdminTerpilih = ""; // Penampung ID sementara
private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Admin");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Status Penggunaan");
        tblAkun.setModel(model);

        try {
            Database db = new Database();
            ResultSet rs = (ResultSet) db.readDB("*", "admin", "1=1");
            
            while (rs != null && rs.next()) {
                String id = rs.getString("id_admin");
                String user = rs.getString("username");
                
                String status = "Tersedia / Admin Utama"; 
                Database dbCek = new Database();
                
                // MENGINTIP NAMA MAHASISWA
                ResultSet rsMhs = (ResultSet) dbCek.readDB("nim, nama_mhs", "mahasiswa", "id_user = '" + id + "'");
                if (rsMhs != null && rsMhs.next()) {
                    status = "Mahasiswa: " + rsMhs.getString("nama_mhs"); // Langsung tampilkan namanya!
                } else {
                    // MENGINTIP NAMA DOSEN
                    ResultSet rsDsn = (ResultSet) dbCek.readDB("nidn, nama_dosen", "dosen", "id_user = '" + id + "'");
                    if (rsDsn != null && rsDsn.next()) {
                        status = "Dosen: " + rsDsn.getString("nama_dosen"); // Langsung tampilkan namanya!
                    }
                }
                
                model.addRow(new Object[]{id, user, "********", status});
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat akun: " + e.getMessage());
        }
    }
    
    /**
     * Creates new form PanelAkun
     */
    public PanelAkun() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAkun = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        cbShowPassword = new javax.swing.JCheckBox();
        lblStatus = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        jLabel1.setText("Kelola Akun");

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        tblAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblAkunMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblAkun);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbShowPassword)
                            .addComponent(btnCari)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbShowPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbShowPassword.isSelected()) {
        txtPassword.setEchoChar((char) 0);
    } else {
        txtPassword.setEchoChar('*');
    }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String user = txtUsername.getText();
    String pass = new String(txtPassword.getPassword());

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
        return;
    }

    Database db = new Database();
    // Validasi: Cek apakah username sudah ada
    try {
        ResultSet rsCek = (ResultSet) db.readDB("username", "admin", "username = '" + user + "'");
        if (rsCek != null && rsCek.next()) {
            JOptionPane.showMessageDialog(this, "Username '" + user + "' sudah terdaftar! Gunakan yang lain.");
            return;
        }
    } catch (Exception e) {}

    if (db.createDB("admin", "username, password", "'" + user + "', '" + pass + "'")) {
        JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!");
        tampilData();
        btnResetActionPerformed(evt);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
     
       // 1. Ambil kata kunci, hapus spasi (trim), dan kecilkan huruf
        String keyword = txtCari.getText().toLowerCase().trim();
        DefaultTableModel model = (DefaultTableModel) tblAkun.getModel();
        model.setRowCount(0); 

        if (keyword.isEmpty()) {
            tampilData();
            return;
        }

        try {
            Database db = new Database();
            // 2. Ambil SEMUA akun dari tabel admin
            java.sql.ResultSet rs = (java.sql.ResultSet) db.readDB("*", "admin", "1=1");
            
            while (rs != null && rs.next()) {
                String id = rs.getString("id_admin");
                String user = rs.getString("username");
                String status = "Tersedia / Admin Utama"; 
                
                // 3. Cek apakah akun ini milik Mahasiswa
                Database dbMhs = new Database();
                java.sql.ResultSet rsMhs = (java.sql.ResultSet) dbMhs.readDB("nama_mhs", "mahasiswa", "id_user = '" + id + "'");
                
                if (rsMhs != null && rsMhs.next()) {
                    status = "Mahasiswa: " + rsMhs.getString("nama_mhs");
                } else {
                    // 4. Cek apakah milik Dosen
                    Database dbDsn = new Database();
                    java.sql.ResultSet rsDsn = (java.sql.ResultSet) dbDsn.readDB("nama_dosen", "dosen", "id_user = '" + id + "'");
                    if (rsDsn != null && rsDsn.next()) {
                        status = "Dosen: " + rsDsn.getString("nama_dosen");
                    }
                }
                
                // --- LOGIKA PENCARIAN GLOBAL ---
                // Sekarang kita bandingkan keyword dengan Username ATAU Nama (Status)
                if (user.toLowerCase().contains(keyword) || status.toLowerCase().contains(keyword)) {
                    model.addRow(new Object[]{id, user, "********", status});
                }
            }
            
            if (model.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data '" + keyword + "' tidak ditemukan!");
                tampilData();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtUsername.setText("");
        txtPassword.setText("");
        lblStatus.setText("Status: -");
        lblStatus.setForeground(java.awt.Color.BLACK);
        if (txtCari != null) txtCari.setText(""); // Mengosongkan kolom pencarian jika ada
        // Tambahkan di dalam btnResetActionPerformed
        idAdminTerpilih = "";
        
        // Buka lagi gembok username untuk bikin akun baru
        txtUsername.setEditable(true); 
        txtUsername.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAkunMouseClicked
        // TODO add your handling code here:
     int baris = tblAkun.getSelectedRow();
        if (baris != -1) {
            idAdminTerpilih = tblAkun.getValueAt(baris, 0).toString();
            String idUser = tblAkun.getValueAt(baris, 0).toString();
            txtUsername.setText(tblAkun.getValueAt(baris, 1).toString());
            txtPassword.setText("");
            txtUsername.setEditable(false);

            try {
                Database db = new Database();
                
                // AMBIL NAMA MAHASISWA
                java.sql.ResultSet rsMhs = (java.sql.ResultSet) db.readDB("nim, nama_mhs", "mahasiswa", "id_user = '" + idUser + "'");
                if (rsMhs != null && rsMhs.next()) {
                    lblStatus.setText("Status: Dipakai oleh " + rsMhs.getString("nama_mhs"));
                    lblStatus.setForeground(java.awt.Color.RED); 
                } else {
                    // AMBIL NAMA DOSEN
                    java.sql.ResultSet rsDosen = (java.sql.ResultSet) db.readDB("nidn, nama_dosen", "dosen", "id_user = '" + idUser + "'");
                    if (rsDosen != null && rsDosen.next()) {
                        lblStatus.setText("Status: Dipakai oleh " + rsDosen.getString("nama_dosen"));
                        lblStatus.setForeground(java.awt.Color.RED);
                    } else {
                        lblStatus.setText("Status: Tersedia / Belum Terpakai");
                        lblStatus.setForeground(new java.awt.Color(0, 153, 0)); 
                    }
                }
            } catch (Exception e) {
                lblStatus.setText("Status: Gagal mengecek data");
            }
        }
    }//GEN-LAST:event_tblAkunMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String user = txtUsername.getText();
        String pass = new String(txtPassword.getPassword());
        
        if (txtUsername.isEditable() || idAdminTerpilih.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih akun di tabel dulu!"); 
            return;
        }

        if (pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ketik password baru jika ingin mereset password akun ini!"); 
            return;
        }

        Database db = new Database();
        // Sekarang kita mengubah password berdasarkan ID ADMIN, pasti langsung tembus!
        if (db.updateDB("admin", "password = '" + pass + "'", "id_admin = '" + idAdminTerpilih + "'")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password untuk akun " + user + " berhasil diubah!");
            tampilData(); 
            btnResetActionPerformed(evt);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah password!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (tblAkun.getSelectedRow() == -1 || idAdminTerpilih.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih akun di tabel dulu!"); 
            return;
        }

        // PROTEKSI KELAS KAKAP: Jangan izinkan hapus akun kalau sedang dipakai Mahasiswa/Dosen
        String statusSaatIni = lblStatus.getText();
        if (statusSaatIni.contains("Terpakai")) {
            javax.swing.JOptionPane.showMessageDialog(this, "AKSES DITOLAK: Akun ini sedang diikat ke data Mahasiswa/Dosen!\nJika ingin menghapus, silakan hapus data Mahasiswa/Dosen yang bersangkutan di panelnya masing-masing.", "Peringatan Keamanan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String user = txtUsername.getText();
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus akun '" + user + "'?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            // Hapus berdasarkan ID agar presisi 100%
            if (db.deleteDB("admin", "id_admin = '" + idAdminTerpilih + "'")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Akun berhasil dihapus!");
                tampilData(); 
                btnResetActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus akun!");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAkunMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAkunMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblAkun;
    private javax.swing.JTextField txtCari;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
