/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelDashboard extends javax.swing.JPanel {
private void loadStatistik() {
        try {
            Database db = new Database();
            java.sql.ResultSet rs;

            // 1. Hitung Total Mahasiswa
            rs = db.readDBSafe("SELECT COUNT(nim) AS total FROM mahasiswa");
            if (rs != null && rs.next()) lblTotalMhs.setText(rs.getString("total"));

            // 2. Hitung Total Dosen
            rs = db.readDBSafe("SELECT COUNT(nidn) AS total FROM dosen");
            if (rs != null && rs.next()) lblTotalDosen.setText(rs.getString("total"));

            // 3. Hitung Total Kelas Terbuka
            rs = db.readDBSafe("SELECT COUNT(id_kelas) AS total FROM kelas WHERE id_periode = (SELECT id_periode FROM periode WHERE status_krs = 'Buka' LIMIT 1)");
            if (rs != null && rs.next()) lblTotalKelas.setText(rs.getString("total"));

            // 4. Hitung Total KRS yang Menunggu Validasi (Penting untuk Admin pantau)
            rs = db.readDBSafe("SELECT COUNT(id_krs) AS total FROM krs_header WHERE status_validasi = 'Menunggu'");
            if (rs != null && rs.next()) {
                String krsPending = rs.getString("total");
                lblKrsPending.setText(krsPending);
                
                // Tambahan pemanis UX: Jika ada KRS numpuk, beri warna merah pada angka
                if (Integer.parseInt(krsPending) > 0) {
                    lblKrsPending.setForeground(java.awt.Color.RED);
                } else {
                    lblKrsPending.setForeground(new java.awt.Color(0, 153, 0)); // Hijau aman
                }
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat statistik dashboard: " + e.getMessage());
        }
    }
    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        loadStatistik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalMhs = new javax.swing.JLabel();
        lblTotalDosen = new javax.swing.JLabel();
        lblTotalKelas = new javax.swing.JLabel();
        lblKrsPending = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lblTotalMhs.setText("0");

        lblTotalDosen.setText("0");

        lblTotalKelas.setText("0");

        lblKrsPending.setText("0");

        jLabel1.setText("Mahasiswa");

        jLabel2.setText("Dosen");

        jLabel3.setText("Kelas");

        jLabel4.setText("KRS Pending");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTotalMhs))
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTotalDosen))
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTotalKelas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblKrsPending)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalMhs))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalDosen))
                    .addComponent(lblTotalKelas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKrsPending)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblKrsPending;
    private javax.swing.JLabel lblTotalDosen;
    private javax.swing.JLabel lblTotalKelas;
    private javax.swing.JLabel lblTotalMhs;
    // End of variables declaration//GEN-END:variables
}
