/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PanelProdi extends javax.swing.JPanel {
    
// Method untuk menampilkan data ke tabel
 private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Prodi"); model.addColumn("Nama Prodi");
        tblProdi.setModel(model);

        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT * FROM prodi");
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{ rs.getString("id_prodi"), rs.getString("nama_prodi") });
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }

    private void autoNumber() {
        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT MAX(id_prodi) AS max_id FROM prodi");
            if (rs != null && rs.next()) {
                int idBaru = rs.getInt("max_id") + 1; 
                txtIdProdi.setText(String.valueOf(idBaru));
            } else {
                txtIdProdi.setText("1"); 
            }
            txtIdProdi.setEditable(false); 
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }
    /**
     * Creates new form PanelProdi
     */
    public PanelProdi() {
        initComponents();
        tampilData();
        autoNumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdProdi = new javax.swing.JTextField();
        txtNamaProdi = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdi = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        jLabel1.setText("Kelola Data Prodi");

        jLabel2.setText("ID Prodi");

        jLabel4.setText("Nama Prodi");

        txtIdProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdiActionPerformed(evt);
            }
        });

        txtNamaProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProdiActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Prodi", "Nama Prodi"
            }
        ));
        tblProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdi);

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaProdi)
                                    .addComponent(txtIdProdi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel1)))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdiActionPerformed

    private void txtNamaProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProdiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
String id = txtIdProdi.getText();
        if (tblProdi.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus!"); return;
        }
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus data prodi ini?", "Konfirmasi", 0) == 0) {
            Database db = new Database();
            if (db.executeDBSafe("DELETE FROM prodi WHERE id_prodi = ?", id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                tampilData(); btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
       String id = txtIdProdi.getText();
        String nama = txtNamaProdi.getText();
        if (id.isEmpty() || nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID dan Nama Prodi tidak boleh kosong!"); return;
        }

        Database db = new Database();
        if (btnSimpan.getText().equals("Simpan")) {
            if (db.executeDBSafe("INSERT INTO prodi (id_prodi, nama_prodi) VALUES (?, ?)", id, nama)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                tampilData(); btnResetActionPerformed(evt); 
            }
        } else {
            if (tblProdi.getSelectedRow() == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan klik data di tabel terlebih dahulu!"); return;
            }
            if (db.executeDBSafe("UPDATE prodi SET nama_prodi = ? WHERE id_prodi = ?", nama, id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                tampilData(); btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdiMouseClicked
        // TODO add your handling code here:
        
        btnSimpan.setText("Ubah Data");
        int baris = tblProdi.getSelectedRow();
        if (baris != -1) {
            // Mengambil data dari baris yang diklik dan memasukkannya ke textfield
            txtIdProdi.setText(tblProdi.getValueAt(baris, 0).toString());
            txtNamaProdi.setText(tblProdi.getValueAt(baris, 1).toString());
            txtIdProdi.setEditable(false);
        }
    }//GEN-LAST:event_tblProdiMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tampilData();
        txtCari.setText("");
        btnSimpan.setText("Simpan");
        // Ganti tblMahasiswa dengan nama tabel di panel yang sedang kamu edit
        tblProdi.clearSelection();
        txtIdProdi.setText("");
        txtNamaProdi.setText("");
        txtIdProdi.requestFocus();
        autoNumber();
        
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword = "%" + txtCari.getText().trim() + "%";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblProdi.getModel();
        model.setRowCount(0); 
        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT * FROM prodi WHERE id_prodi LIKE ? OR nama_prodi LIKE ?", keyword, keyword);
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{ rs.getString("id_prodi"), rs.getString("nama_prodi") });
            }
            if (model.getRowCount() == 0) tampilData();
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdProdi;
    private javax.swing.JTextField txtNamaProdi;
    // End of variables declaration//GEN-END:variables
}
