/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelJadwalMahasiswa extends javax.swing.JPanel {

    /**
     * Creates new form PanelJadwalMahasiswa
     */
    public PanelJadwalMahasiswa() {
        initComponents();
        setupTabel();
        loadJadwal();
    }
    
    private javax.swing.table.DefaultTableModel modelJadwal;

    private void setupTabel() {
        modelJadwal = new javax.swing.table.DefaultTableModel(new String[]{
            "No", "Hari", "Jam", "Ruang", "Mata Kuliah", "SKS", "Dosen"
        }, 0);
        tblJadwal.setModel(modelJadwal);
        
        // Mempersempit kolom "No" dan "SKS" agar tabel terlihat rapi
        tblJadwal.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblJadwal.getColumnModel().getColumn(5).setPreferredWidth(40);
    }

    private void loadJadwal() {
        try {
            Database db = new Database();
            
            // 1. Cek periode mana yang sedang aktif
            String idPeriodeAktif = "";
            java.sql.ResultSet rsPeriode = db.readDBSafe("SELECT id_periode, semester, tahun_ajaran FROM periode WHERE status_krs = 'Buka' LIMIT 1");
            if (rsPeriode != null && rsPeriode.next()) {
                idPeriodeAktif = rsPeriode.getString("id_periode");
                lblHeader.setText("Jadwal Kuliah - " + rsPeriode.getString("semester") + " " + rsPeriode.getString("tahun_ajaran"));
            } else {
                lblHeader.setText("Tidak ada periode aktif.");
                return; // Stop jika sedang libur semester
            }

            // 2. Cek apakah KRS mahasiswa ini sudah "Disetujui"
            String nim = Login.getUserLogin(); 
            java.sql.ResultSet rsStatus = db.readDBSafe("SELECT status_validasi FROM krs_header WHERE nim = ? AND id_periode = ?", nim, idPeriodeAktif);
            
            boolean isDisetujui = false;
            if (rsStatus != null && rsStatus.next()) {
                if ("Disetujui".equals(rsStatus.getString("status_validasi"))) {
                    isDisetujui = true;
                }
            }

            // 3. Jika belum disetujui, blokir akses jadwal
            if (!isDisetujui) {
        lblHeader.setText("Jadwal Belum Tersedia (KRS Menunggu Validasi)");
        modelJadwal.setRowCount(0); // Kosongkan tabel
        return;
    }

            // 4. Jika sudah disetujui, load jadwal dan urutkan berdasarkan Hari & Jam
            String sql = "SELECT mk.kode_mk, mk.nama_mk, mk.sks, k.hari, k.jam, k.ruang, d.nama_dosen " +
                         "FROM krs_detail kd " +
                         "JOIN krs_header kh ON kd.id_krs = kh.id_krs " +
                         "JOIN kelas k ON kd.id_kelas = k.id_kelas " +
                         "JOIN mata_kuliah mk ON k.kode_mk = mk.kode_mk " +
                         "JOIN dosen d ON k.nidn = d.nidn " +
                         "WHERE kh.nim = ? AND kh.id_periode = ? AND kh.status_validasi = 'Disetujui' " +
                         "ORDER BY FIELD(k.hari,'Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'), k.jam";
            
            java.sql.ResultSet rs = db.readDBSafe(sql, nim, idPeriodeAktif);
            modelJadwal.setRowCount(0); // Bersihkan tabel
            
            int no = 1;
            int totalSks = 0;
            while (rs != null && rs.next()) {
                int sks = rs.getInt("sks");
                modelJadwal.addRow(new Object[]{
                    no++,
                    rs.getString("hari"),
                    rs.getString("jam"),
                    rs.getString("ruang"),
                    rs.getString("kode_mk") + " - " + rs.getString("nama_mk"),
                    sks,
                    rs.getString("nama_dosen")
                });
                totalSks += sks;
            }
            lblTotalSks.setText("Total SKS: " + totalSks);

        } catch (Exception e) {
            System.err.println("Gagal memuat jadwal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        lblTotalSks = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblHeader.setText("Jadwal Kuliah Semester Ini");

        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJadwal);

        lblTotalSks.setText("0");

        jLabel1.setText("Total SKS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalSks)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSks)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblTotalSks;
    private javax.swing.JTable tblJadwal;
    // End of variables declaration//GEN-END:variables
}
