/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelAccKRS extends javax.swing.JPanel {

    /**
     * Creates new form PanelAccKRS
     */
    public PanelAccKRS() {
        initComponents();
        tampilDataPending();
    }
    
    private void tampilDataPending() {
        // 1. Buat kerangka kolom tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID KRS");
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Total SKS");
        model.addColumn("Tanggal");
        tblKrsPending.setModel(model);

        // 2. Tarik data dari database
        try {
            Database db = new Database();
            // Mengambil KRS yang statusnya masih 'Menunggu' beserta nama mahasiswanya
            String sql = "SELECT k.id_krs, k.nim, m.nama_mhs, k.total_sks, k.tgl_pengajuan " +
                         "FROM krs_header k JOIN mahasiswa m ON k.nim = m.nim " +
                         "WHERE k.status_validasi = 'Menunggu'";
                         
            java.sql.ResultSet rs = db.readDBSafe(sql);
            
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_krs"),
                    rs.getString("nim"),
                    rs.getString("nama_mhs"),
                    rs.getString("total_sks"),
                    rs.getString("tgl_pengajuan")
                });
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat data KRS pending: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKrsPending = new javax.swing.JTable();
        btnSetuju = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jLabel1.setText("Daftar Pengajuan KRS (Menunggu Validasi)");

        tblKrsPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKrsPending);

        btnSetuju.setText("Setujui KRS");
        btnSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuActionPerformed(evt);
            }
        });

        btnTolak.setText("Tolak / Kembalikan");
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSetuju)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTolak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetuju)
                    .addComponent(btnTolak)
                    .addComponent(btnRefresh))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuActionPerformed
        // TODO add your handling code here:
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin MENYETUJUI KRS milik " + namaMhs + "?", "Konfirmasi Validasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            if (db.executeDBSafe("UPDATE krs_header SET status_validasi = 'Disetujui' WHERE id_krs = ?", idKrs)) {
                javax.swing.JOptionPane.showMessageDialog(this, "KRS Berhasil Disetujui!");
                tampilDataPending(); // Segarkan tabel
            }
        }
    }//GEN-LAST:event_btnSetujuActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
        // TODO add your handling code here:
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin MENOLAK KRS milik " + namaMhs + "?", "Konfirmasi Validasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            if (db.executeDBSafe("UPDATE krs_header SET status_validasi = 'Ditolak' WHERE id_krs = ?", idKrs)) {
                javax.swing.JOptionPane.showMessageDialog(this, "KRS telah Ditolak/Dibatalkan.");
                tampilDataPending(); // Segarkan tabel
            }
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilDataPending();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSetuju;
    private javax.swing.JButton btnTolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKrsPending;
    // End of variables declaration//GEN-END:variables
}
