/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelDashboard extends javax.swing.JPanel {
private void loadStatistik() {
        try {
            Database db = new Database();
            java.sql.ResultSet rs;

            // 1. Hitung Total Mahasiswa
            rs = db.readDBSafe("SELECT COUNT(nim) AS total FROM mahasiswa");
            if (rs != null && rs.next()) lblTotalMhs.setText(rs.getString("total"));

            // 2. Hitung Total Dosen
            rs = db.readDBSafe("SELECT COUNT(nidn) AS total FROM dosen");
            if (rs != null && rs.next()) lblTotalDosen.setText(rs.getString("total"));

            // 3. Hitung Total Kelas Terbuka
            rs = db.readDBSafe("SELECT COUNT(id_kelas) AS total FROM kelas WHERE id_periode = (SELECT id_periode FROM periode WHERE status_krs = 'Buka' LIMIT 1)");
            if (rs != null && rs.next()) lblTotalKelas.setText(rs.getString("total"));

            // 4. Hitung Total KRS yang Menunggu Validasi (Penting untuk Admin pantau)
            rs = db.readDBSafe("SELECT COUNT(id_krs) AS total FROM krs_header WHERE status_validasi = 'Menunggu'");
            if (rs != null && rs.next()) {
                String krsPending = rs.getString("total");
                lblKrsPending.setText(krsPending);
                
                // Tambahan pemanis UX: Jika ada KRS numpuk, beri warna merah pada angka
                if (Integer.parseInt(krsPending) > 0) {
                    lblKrsPending.setForeground(java.awt.Color.RED);
                } else {
                    lblKrsPending.setForeground(new java.awt.Color(0, 153, 0)); // Hijau aman
                }
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat statistik dashboard: " + e.getMessage());
        }
    }
    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        loadStatistik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalMhs = new javax.swing.JLabel();
        lblTotalDosen = new javax.swing.JLabel();
        lblTotalKelas = new javax.swing.JLabel();
        lblKrsPending = new javax.swing.JLabel();

        jLabel4.setText("Mahasiswa");

        jLabel6.setText("Dosen");

        jLabel7.setText("Kelas");

        jLabel8.setText("KRS Pending");

        lblTotalMhs.setText("0");

        lblTotalDosen.setText("0");

        lblTotalKelas.setText("0");

        lblKrsPending.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTotalMhs)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblTotalDosen)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTotalKelas))
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblKrsPending)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalMhs)
                    .addComponent(lblTotalDosen)
                    .addComponent(lblTotalKelas)
                    .addComponent(lblKrsPending))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblKrsPending;
    private javax.swing.JLabel lblTotalDosen;
    private javax.swing.JLabel lblTotalKelas;
    private javax.swing.JLabel lblTotalMhs;
    // End of variables declaration//GEN-END:variables
}
