/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author ACER
 */
public class PanelBimbinganDosen extends javax.swing.JPanel {

    private String idPeriodeAktif = "";

    private void loadTabelBimbingan() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(new String[]{"NIM", "Nama Mahasiswa", "Status KRS"}, 0);
        tblBimbingan.setModel(model);
        
        try {
            Database db = new Database();
            // Cari Periode
            java.sql.ResultSet rsPeriode = db.readDBSafe("SELECT id_periode FROM periode WHERE status_krs = 'Buka' LIMIT 1");
            if (rsPeriode != null && rsPeriode.next()) {
                idPeriodeAktif = rsPeriode.getString("id_periode");
            } else {
                return; // Berhenti jika tidak ada periode
            }

            // Cari Data Bimbingan
            String nidn = Login.getUserLogin();
            String sql = "SELECT m.nim, m.nama_mhs, COALESCE(k.status_validasi, 'Belum Isi') AS status_krs " +
                         "FROM mahasiswa m LEFT JOIN krs_header k ON m.nim = k.nim AND k.id_periode = ? " +
                         "WHERE m.id_dosen_wali = ? ORDER BY m.nama_mhs ASC";
            
            java.sql.ResultSet rs = db.readDBSafe(sql, idPeriodeAktif, nidn);
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{rs.getString("nim"), rs.getString("nama_mhs"), rs.getString("status_krs")});
            }
        } catch (Exception e) {
            System.err.println("Gagal load tabel bimbingan: " + e.getMessage());
        }
    }
    /**
     * Creates new form PanelBimbinganDosen
     */
    public PanelBimbinganDosen() {
        initComponents();
        loadTabelBimbingan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBimbingan = new javax.swing.JTable();
        btnCetakKrsMhs = new javax.swing.JButton();

        tblBimbingan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBimbingan);

        btnCetakKrsMhs.setText("Cetak KRS");
        btnCetakKrsMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKrsMhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCetakKrsMhs)
                        .addContainerGap(311, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakKrsMhs)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakKrsMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKrsMhsActionPerformed
        // TODO add your handling code here:
        // 1. Validasi Baris Tabel (Pencegah ArrayIndexOutOfBoundsException)
        int row = tblBimbingan.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu mahasiswa dari tabel terlebih dahulu!");
            return;
        }

        // 2. Ambil NIM dari kolom ke-0 pada baris yang dipilih
        String nimTerpilih = tblBimbingan.getValueAt(row, 0).toString();

        // 3. Validasi Keamanan Variabel Periode Aktif
        // (Pastikan variabel idPeriodeAktif sudah diisi oleh fungsi loadTabelBimbingan())
        if (idPeriodeAktif == null || idPeriodeAktif.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada periode aktif atau sistem gagal memuat periode.");
            return;
        }

        try {
            // 4. Cek Koneksi Database
            Database db = new Database();
            if (db.getConnection() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "GAGAL: Koneksi Database terputus!");
                return;
            }

            // 5. Siapkan Parameter Jasper (TRIPLE-LOCK SECURITY)
            java.util.HashMap<String, Object> parameter = new java.util.HashMap<>();
            parameter.put("p_nim", nimTerpilih); // Dari pilihan tabel UI
            parameter.put("p_id_periode", idPeriodeAktif); // Dari state sistem
            parameter.put("p_nidn_dosen", Login.getUserLogin()); // OTORITAS MUTLAK DARI SESI LOGIN
            
            // 6. Cari Lokasi File JRXML
            java.io.File file = new java.io.File("src/main/java/com/mycompany/krs/CetakKrsBimbingan.jrxml");
            
            if (!file.exists()) {
                file = new java.io.File("src/com/mycompany/krs/CetakKrsBimbingan.jrxml");
            }
            
            if (!file.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this, "GAGAL: File CetakKrsBimbingan.jrxml tidak ditemukan!");
                return;
            }
            
            // 7. Proses Compile & Baca File
            java.io.InputStream fileJrxml = new java.io.FileInputStream(file);
            net.sf.jasperreports.engine.JasperReport jasperReport = net.sf.jasperreports.engine.JasperCompileManager.compileReport(fileJrxml);
            
            // 8. Isi Laporan dengan Data
            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperReport, parameter, db.getConnection());
            
            // 9. Cegah Laporan Kosong
            if (jasperPrint.getPages().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Dokumen kosong! Mahasiswa ini belum mengambil matkul atau bukan bimbingan Anda.");
                return;
            }
            
            // 10. Tampilkan Layar Pratinjau (Preview PDF)
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            String namaError = e.toString();
            String barisError = (e.getStackTrace().length > 0) ? e.getStackTrace()[0].toString() : "Tidak diketahui";
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Error Detail:\n" + namaError + "\n\nLokasi: " + barisError);
        }
    }//GEN-LAST:event_btnCetakKrsMhsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakKrsMhs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBimbingan;
    // End of variables declaration//GEN-END:variables
}
