/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class PanelAkun extends javax.swing.JPanel {
private String idAdminTerpilih = ""; // Penampung ID sementara
private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Admin"); model.addColumn("Username");
        model.addColumn("Password"); model.addColumn("Status Penggunaan");
        tblAkun.setModel(model);

        try {
            Database db = new Database();
            // SUPER CEPAT: 1x panggil database langsung dapet semuanya
            String sql = "SELECT a.id_admin, a.username, m.nama_mhs, d.nama_dosen FROM admin a " +
                         "LEFT JOIN mahasiswa m ON m.id_user = a.id_admin " +
                         "LEFT JOIN dosen d ON d.id_user = a.id_admin";
            java.sql.ResultSet rs = db.readDBSafe(sql);
            
            while (rs != null && rs.next()) {
                String status = "Tersedia / Admin Utama";
                if (rs.getString("nama_mhs") != null) status = "Mahasiswa: " + rs.getString("nama_mhs");
                else if (rs.getString("nama_dosen") != null) status = "Dosen: " + rs.getString("nama_dosen");
                
                model.addRow(new Object[]{rs.getString("id_admin"), rs.getString("username"), "********", status});
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }
    
    /**
     * Creates new form PanelAkun
     */
    public PanelAkun() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAkun = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        cbShowPassword = new javax.swing.JCheckBox();
        lblStatus = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        jLabel1.setText("Tabel Akun");

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        tblAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblAkunMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblAkun);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cbShowPassword.setText("Show Password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbShowPassword)
                                    .addComponent(btnCari))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbShowPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbShowPassword.isSelected()) {
        txtPassword.setEchoChar((char) 0);
    } else {
        txtPassword.setEchoChar('*');
    }
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
String user = txtUsername.getText().trim();
        String pass = new String(txtPassword.getPassword());
        if (user.isEmpty() || pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!"); return;
        }

        Database db = new Database();
        if (btnSimpan.getText().equals("Simpan")) {
            try {
                java.sql.ResultSet rsCek = db.readDBSafe("SELECT username FROM admin WHERE username = ?", user);
                if (rsCek != null && rsCek.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Username sudah terdaftar!"); return;
                }
                
                // ---> FIX INSERT: Gunakan Database.hashPassword(pass)
                if (db.executeDBSafe("INSERT INTO admin (username, password) VALUES (?, ?)", user, Database.hashPassword(pass))) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!");
                    btnResetActionPerformed(evt);
                }
            } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
        } else {
            if (idAdminTerpilih.isEmpty()) return;
            
            // ---> FIX UPDATE: Gunakan Database.hashPassword(pass)
            if (db.executeDBSafe("UPDATE admin SET password = ? WHERE id_admin = ?", Database.hashPassword(pass), idAdminTerpilih)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Password berhasil diubah!");
                btnResetActionPerformed(evt);
            }
        }
 
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
     
       String keyword = "%" + txtCari.getText().trim() + "%";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAkun.getModel();
        model.setRowCount(0); 
        try {
            Database db = new Database();
            String sql = "SELECT a.id_admin, a.username, m.nama_mhs, d.nama_dosen FROM admin a " +
                         "LEFT JOIN mahasiswa m ON m.id_user = a.id_admin " +
                         "LEFT JOIN dosen d ON d.id_user = a.id_admin " +
                         "WHERE a.username LIKE ? OR m.nama_mhs LIKE ? OR d.nama_dosen LIKE ?";
            java.sql.ResultSet rs = db.readDBSafe(sql, keyword, keyword, keyword);
            
            while (rs != null && rs.next()) {
                String status = "Tersedia / Admin Utama";
                if (rs.getString("nama_mhs") != null) status = "Mahasiswa: " + rs.getString("nama_mhs");
                else if (rs.getString("nama_dosen") != null) status = "Dosen: " + rs.getString("nama_dosen");
                model.addRow(new Object[]{rs.getString("id_admin"), rs.getString("username"), "********", status});
            }
            if (model.getRowCount() == 0) tampilData();
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tampilData();
        txtCari.setText("");
        btnSimpan.setText("Simpan");
        // Ganti tblMahasiswa dengan nama tabel di panel yang sedang kamu edit
        tblAkun.clearSelection();
        txtUsername.setText("");
        txtPassword.setText("");
        lblStatus.setText("Status: -");
        lblStatus.setForeground(java.awt.Color.BLACK);
        if (txtCari != null) txtCari.setText(""); // Mengosongkan kolom pencarian jika ada
        // Tambahkan di dalam btnResetActionPerformed
        idAdminTerpilih = "";
        
        // Buka lagi gembok username untuk bikin akun baru
        txtUsername.setEditable(true); 
        txtUsername.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAkunMouseClicked
        // TODO add your handling code here:
     int baris = tblAkun.getSelectedRow();
        if (baris != -1) {
            idAdminTerpilih = tblAkun.getValueAt(baris, 0).toString();
            txtUsername.setText(tblAkun.getValueAt(baris, 1).toString());
            txtPassword.setText("");
            txtUsername.setEditable(false);
            
            String status = tblAkun.getValueAt(baris, 3).toString();
            lblStatus.setText("Status: " + status);
            lblStatus.setForeground(status.contains("Tersedia") ? new java.awt.Color(0, 153, 0) : java.awt.Color.RED);
            btnSimpan.setText("Ubah Data");
        }
    }//GEN-LAST:event_tblAkunMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
       if (idAdminTerpilih.isEmpty()) return;
        if (lblStatus.getText().contains("Mahasiswa") || lblStatus.getText().contains("Dosen")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Akses Ditolak: Akun sedang dipakai Mahasiswa/Dosen!"); return;
        }
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus?", "Konfirmasi", 0) == 0) {
            Database db = new Database();
            if (db.executeDBSafe("DELETE FROM admin WHERE id_admin = ?", idAdminTerpilih)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Akun dihapus!");
                btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAkunMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAkunMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblAkun;
    private javax.swing.JTextField txtCari;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
