/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author natha
 */
public class PanelMatkul extends javax.swing.JPanel {
private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Kode MK"); model.addColumn("Nama Mata Kuliah");
        model.addColumn("SKS"); model.addColumn("Semester");
        tblMatkul.setModel(model);

        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT * FROM mata_kuliah");
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{ rs.getString("kode_mk"), rs.getString("nama_mk"), rs.getString("sks"), rs.getString("semester") });
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }


    /**
     * Creates new form PanelKelolaMataKuliah
     */
    public PanelMatkul() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeMk = new javax.swing.JTextField();
        txtNamaMk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatkul = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSks = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        jLabel1.setText("Kelola Data Mata Kuliah");

        jLabel2.setText("Kode Mata Kuliah");

        jLabel3.setText("Nama Mata Kuliah");

        txtKodeMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMkActionPerformed(evt);
            }
        });

        tblMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Mata Kuliah", "Nama Mata Kuliah", "SKS", "Semester"
            }
        ));
        tblMatkul.setAutoscrolls(false);
        tblMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMatkul);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel4.setText("SKS");

        jLabel5.setText("Semester");

        txtSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSksActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtKodeMk, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                                .addComponent(txtNamaMk)
                                                .addComponent(txtSks)
                                                .addComponent(txtSemester))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReset)))
                                .addGap(0, 29, Short.MAX_VALUE)))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMkActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        String kode = txtKodeMk.getText().trim();
        String nama = txtNamaMk.getText().trim();
        String sks = txtSks.getText().trim();
        String semester = txtSemester.getText().trim();
        
        // 1. CEK KOLOM KOSONG
        if (kode.isEmpty() || nama.isEmpty() || sks.isEmpty() || semester.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!"); return;
        }

        // 2. CEK SKS DAN SEMESTER HARUS ANGKA (Anti-Error Database)
        try {
            Integer.parseInt(sks);
            Integer.parseInt(semester);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal! Kolom SKS dan Semester harus diisi dengan Angka Bulat."); 
            return;
        }

        Database db = new Database();
        if (btnSimpan.getText().equals("Simpan")) {
            try {
                // 3. CEK KODE MK DUPLIKAT (Tidak boleh ada kode yang sama persis)
                java.sql.ResultSet rsCek = db.readDBSafe("SELECT kode_mk FROM mata_kuliah WHERE kode_mk = ?", kode);
                if (rsCek != null && rsCek.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal! Kode Mata Kuliah '" + kode + "' sudah terdaftar di database."); 
                    return;
                }

                // JIKA SEMUA AMAN, SIMPAN KE DATABASE
                if (db.executeDBSafe("INSERT INTO mata_kuliah (kode_mk, nama_mk, sks, semester) VALUES (?, ?, ?, ?)", kode, nama, sks, semester)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                    tampilData(); btnResetActionPerformed(evt); 
                }
            } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
            
        } else {
            // MODE UBAH DATA
            if (txtKodeMk.isEditable()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Klik data di tabel yang ingin diubah!"); return;
            }
            if (db.executeDBSafe("UPDATE mata_kuliah SET nama_mk = ?, sks = ?, semester = ? WHERE kode_mk = ?", nama, sks, semester, kode)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                tampilData(); btnResetActionPerformed(evt);
            }
        }
        
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSksActionPerformed

    private void tblMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatkulMouseClicked
        // TODO add your handling code here:
        int baris = tblMatkul.getSelectedRow();
        if (baris != -1) {
            txtKodeMk.setText(tblMatkul.getValueAt(baris, 0).toString());
            txtNamaMk.setText(tblMatkul.getValueAt(baris, 1).toString());
            txtSks.setText(tblMatkul.getValueAt(baris, 2).toString());
            txtSemester.setText(tblMatkul.getValueAt(baris, 3).toString());
            
            // Kunci Kode MK agar tidak diubah
            txtKodeMk.setEditable(false); 
            btnSimpan.setText("Ubah Data");
        }
    }//GEN-LAST:event_tblMatkulMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String kode = txtKodeMk.getText();
        if (txtKodeMk.isEditable()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Klik data di tabel yang ingin dihapus!"); return;
        }
        if (javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus mata kuliah ini?", "Konfirmasi", 0) == 0) {
            Database db = new Database();
            if (db.executeDBSafe("DELETE FROM mata_kuliah WHERE kode_mk = ?", kode)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data dihapus!");
                tampilData(); btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tampilData();
        txtCari.setText("");
        txtKodeMk.setText("");
        txtNamaMk.setText("");
        txtSks.setText("");
        txtSemester.setText("");
        
        txtKodeMk.setEditable(true); // Buka kembali kuncinya untuk input data baru
        txtKodeMk.requestFocus();
        btnSimpan.setText("Simpan");
        // Ganti tblMahasiswa dengan nama tabel di panel yang sedang kamu edit
        tblMatkul.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword = "%" + txtCari.getText().trim() + "%";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMatkul.getModel();
        model.setRowCount(0); 
        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT * FROM mata_kuliah WHERE kode_mk LIKE ? OR nama_mk LIKE ?", keyword, keyword);
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{ rs.getString("kode_mk"), rs.getString("nama_mk"), rs.getString("sks"), rs.getString("semester") });
            }
            if (model.getRowCount() == 0) tampilData();
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMatkul;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKodeMk;
    private javax.swing.JTextField txtNamaMk;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables
}
