/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class PanelDosen extends javax.swing.JPanel {
private void loadComboBox() {
        try {
            Database db = new Database();
            // Hanya mengisi combobox Prodi
            java.sql.ResultSet rsProdi = (java.sql.ResultSet) db.readDB("id_prodi, nama_prodi", "prodi", "1=1");
            cbProdi.removeAllItems();
            while (rsProdi != null && rsProdi.next()) {
                cbProdi.addItem(rsProdi.getString("id_prodi") + " - " + rsProdi.getString("nama_prodi"));
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat pilihan: " + e.getMessage());
        }
    }

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIDN");
        model.addColumn("Nama Dosen");
        model.addColumn("ID Prodi");
        model.addColumn("ID User");
        tblDosen.setModel(model);

        try {
            Database db = new Database();
            ResultSet rs = (ResultSet) db.readDB("*", "dosen", "1=1");
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nidn"),
                    rs.getString("nama_dosen"),
                    rs.getString("id_prodi"),
                    rs.getString("id_user")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * Creates new form PanelDosen
     */
    public PanelDosen() {
        initComponents();
        loadComboBox(); // <--- Panggil ini dulu
        tampilData();   // <--- Baru panggil ini
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNidn = new javax.swing.JTextField();
        txtNamaDosen = new javax.swing.JTextField();
        cbProdi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDosen = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jLabel1.setText("Kelola Dosen");

        jLabel2.setText("NIDN");

        jLabel3.setText("Nama Dosen");

        jLabel4.setText("Pilih Prodi");

        txtNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDosenActionPerformed(evt);
            }
        });

        cbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIDN", "Nama Dosen", "Pilih Prodi", "Pilih Akun Login"
            }
        ));
        tblDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDosen);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(86, 86, 86)
                                .addComponent(txtNidn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNidn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDosenActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:String nidn = txtNidn.getText();
        String nidn = txtNidn.getText();
        String nama = txtNamaDosen.getText();
        String idProdi = cbProdi.getSelectedItem().toString().split(" - ")[0];
        
        if (nidn.isEmpty() || nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "NIDN dan Nama harus diisi!");
            return;
        }

        Database db = new Database();
        try {
            // STEP 1: Cek apakah NIDN sudah terdaftar sebagai akun
            java.sql.ResultSet rsCek = (java.sql.ResultSet) db.readDB("username", "admin", "username = '" + nidn + "'");
            if (rsCek != null && rsCek.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "NIDN ini sudah memiliki akun di sistem!");
                return;
            }

            // STEP 2: Bikin akun Dosen otomatis (Username = NIDN, Password = NIDN)
            boolean akunOk = db.createDB("admin", "username, password", "'" + nidn + "', '" + nidn + "'");
            
            if (akunOk) {
                // STEP 3: Ambil ID Admin dari akun yang baru dibuat
                java.sql.ResultSet rsId = (java.sql.ResultSet) db.readDB("id_admin", "admin", "username = '" + nidn + "'");
                if (rsId != null && rsId.next()) {
                    String idBaru = rsId.getString("id_admin");
                    
                    // STEP 4: Simpan data ke tabel Dosen
                    String kolom = "nidn, nama_dosen, id_prodi, id_user";
                    String nilai = "'" + nidn + "', '" + nama + "', '" + idProdi + "', '" + idBaru + "'";
                    
                    if (db.createDB("dosen", kolom, nilai)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen & Akun Otomatis Berhasil Dibuat!\nUsername: " + nidn + "\nPassword: " + nidn);
                        tampilData();
                        btnResetActionPerformed(evt);
                    }
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Sistem: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       txtNidn.setText("");
        txtNamaDosen.setText("");
        if (cbProdi.getItemCount() > 0) cbProdi.setSelectedIndex(0);
        
        txtNidn.setEditable(true);
        txtNidn.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDosenMouseClicked
        // TODO add your handling code here:
        int baris = tblDosen.getSelectedRow();
        if (baris != -1) {
            txtNidn.setText(tblDosen.getValueAt(baris, 0).toString());
            txtNamaDosen.setText(tblDosen.getValueAt(baris, 1).toString());
            txtNidn.setEditable(false); // Kunci NIDN
            
            // Set Dropdown Prodi (Kolom ke-3, index 2)
            String prodiDicari = tblDosen.getValueAt(baris, 2).toString();
            for (int i = 0; i < cbProdi.getItemCount(); i++) {
                if (cbProdi.getItemAt(i).toString().startsWith(prodiDicari + " -")) {
                    cbProdi.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblDosenMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String nidn = txtNidn.getText();
        String nama = txtNamaDosen.getText();
        String idProdi = cbProdi.getSelectedItem().toString().split(" - ")[0];
        
        if (txtNidn.isEditable()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang mau diubah!"); 
            return;
        }

        Database db = new Database();
        String nilaiUpdate = "nama_dosen = '" + nama + "', id_prodi = '" + idProdi + "'";
        
        if (db.updateDB("dosen", nilaiUpdate, "nidn = '" + nidn + "'")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data dosen berhasil diubah!");
            tampilData(); 
            btnResetActionPerformed(evt);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data dosen!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tblDosen.getSelectedRow();
        if (baris == -1 || txtNidn.isEditable()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang mau dihapus!");
            return;
        }

        String nidn = txtNidn.getText();
        // Ambil ID User dari tabel (Kolom ke-4, index 3) untuk dihapus
        String idUser = tblDosen.getValueAt(baris, 3).toString(); 

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Menghapus Dosen juga akan menghapus Akun Loginnya. Lanjutkan?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            
            // Hapus data dari tabel dosen terlebih dahulu (karena dia 'anak' dari tabel admin)
            if (db.deleteDB("dosen", "nidn = '" + nidn + "'")) {
                // Setelah aman, hapus akun utamanya di tabel admin
                db.deleteDB("admin", "id_admin = '" + idUser + "'");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Dosen dan Akun berhasil dihapus!");
                tampilData();
                btnResetActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDosen;
    private javax.swing.JTextField txtNamaDosen;
    private javax.swing.JTextField txtNidn;
    // End of variables declaration//GEN-END:variables
}
