/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelAccKRS extends javax.swing.JPanel {

    /**
     * Creates new form PanelAccKRS
     */
    public PanelAccKRS() {
        initComponents();
        tampilDataPending();
    }
    
    private void tampilDataPending() {
        // 1. Buat kerangka kolom tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID KRS");
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Total SKS");
        model.addColumn("Tanggal");
        tblKrsPending.setModel(model);

        // 2. Tarik data dari database
        try {
            Database db = new Database();
            
            // 1. Ambil NIDN Dosen yang sedang login
            String dosenLogin = Login.getUserLogin(); 
            
            // 2. Kueri ditambah filter AND m.id_dosen_wali = ? (Sesuai database milikmu)
            String sql = "SELECT k.id_krs, k.nim, m.nama_mhs, k.total_sks, k.tgl_pengajuan " +
                         "FROM krs_header k JOIN mahasiswa m ON k.nim = m.nim " +
                         "WHERE k.status_validasi = 'Menunggu' AND m.id_dosen_wali = ?";
                         
            // 3. Masukkan dosenLogin sebagai pengaman kueri
            java.sql.ResultSet rs = db.readDBSafe(sql, dosenLogin);
            
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_krs"),
                    rs.getString("nim"),
                    rs.getString("nama_mhs"),
                    rs.getString("total_sks"),
                    rs.getString("tgl_pengajuan")
                });
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat data KRS pending: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKrsPending = new javax.swing.JTable();
        btnSetuju = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnValidasi = new javax.swing.JButton();

        jLabel1.setText("Daftar Pengajuan KRS (Menunggu Validasi)");

        tblKrsPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKrsPending);

        btnSetuju.setText("Setujui KRS");
        btnSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetujuActionPerformed(evt);
            }
        });

        btnTolak.setText("Tolak / Kembalikan");
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnValidasi.setText("Validasi Per MK");
        btnValidasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnValidasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSetuju)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTolak)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetuju)
                    .addComponent(btnTolak)
                    .addComponent(btnRefresh)
                    .addComponent(btnDetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValidasi)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuActionPerformed
        // TODO add your handling code here:
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin MENYETUJUI KRS milik " + namaMhs + "?", "Konfirmasi Validasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            if (db.executeDBSafe("UPDATE krs_header SET status_validasi = 'Disetujui' WHERE id_krs = ?", idKrs)) {
                javax.swing.JOptionPane.showMessageDialog(this, "KRS Berhasil Disetujui!");
                tampilDataPending(); // Segarkan tabel
            }
        }
    }//GEN-LAST:event_btnSetujuActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
        // TODO add your handling code here:
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin MENOLAK KRS milik " + namaMhs + "?", "Konfirmasi Validasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // FITUR BARU: Minta Alasan Penolakan ke Dosen
            String catatan = javax.swing.JOptionPane.showInputDialog(this, 
                "Masukkan Alasan Penolakan:\n(Misal: SKS melebihi batas, hapus 1 matkul)", 
                "Catatan Dosen Wali", 
                javax.swing.JOptionPane.QUESTION_MESSAGE);
            
            // Jika dosen menekan tombol 'Cancel' atau menyilang kotak alasan, batalkan penolakan
            if (catatan == null) {
                return; 
            }

            Database db = new Database();
            try {
                if (!db.beginTransaction()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal memulai transaksi!"); return;
                }
                
                // 1. Update status dan masukkan catatan dosen
                boolean okHeader = db.executeDBSafe("UPDATE krs_header SET status_validasi = 'Ditolak', catatan_dosen = ? WHERE id_krs = ?", catatan, idKrs);
                
                // 2. Kembalikan kuota kelas
                boolean okKuota = db.executeDBSafe("UPDATE kelas SET kuota = kuota + 1 WHERE id_kelas IN (SELECT id_kelas FROM krs_detail WHERE id_krs = ?)", idKrs);
                
                // 3. Bersihkan keranjang
                boolean okDetail = db.executeDBSafe("DELETE FROM krs_detail WHERE id_krs = ?", idKrs);

                if (okHeader && okKuota && okDetail) {
                    db.commit();
                    javax.swing.JOptionPane.showMessageDialog(this, "KRS telah Ditolak. Catatan penolakan berhasil dikirim ke mahasiswa!");
                    tampilDataPending();
                } else {
                    db.rollback();
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses penolakan KRS.");
                }
            } catch (Exception e) {
                db.rollback();
                System.err.println("Error tolak KRS: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilDataPending();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        // 1. Ambil baris mahasiswa yang dipilih
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();
        
        try {
            Database db = new Database();
            // 2. Kueri untuk mengambil jadwal matkul dari ID KRS tersebut
            String sql = "SELECT mk.kode_mk, mk.nama_mk, k.hari, k.jam, mk.sks, k.ruang " +
                         "FROM krs_detail kd " +
                         "JOIN kelas k ON kd.id_kelas = k.id_kelas " +
                         "JOIN mata_kuliah mk ON k.kode_mk = mk.kode_mk " +
                         "WHERE kd.id_krs = ?";
            java.sql.ResultSet rs = db.readDBSafe(sql, idKrs);
            
            // 3. Rangkai teks menjadi daftar yang rapi
            StringBuilder detailText = new StringBuilder();
            detailText.append("Jadwal KRS Mahasiswa: ").append(namaMhs).append("\n");
            detailText.append("----------------------------------------------------------------------\n");
            
            int totalSks = 0;
            while (rs != null && rs.next()) {
                detailText.append("- ").append(rs.getString("kode_mk")).append(" | ")
                          .append(rs.getString("nama_mk")).append("\n  Jadwal: ")
                          .append(rs.getString("hari")).append(", ").append(rs.getString("jam"))
                          .append(" (Ruang ").append(rs.getString("ruang")).append(") | ")
                          .append(rs.getString("sks")).append(" SKS\n\n");
                totalSks += rs.getInt("sks");
            }
            detailText.append("----------------------------------------------------------------------\n");
            detailText.append("Total Keseluruhan SKS: ").append(totalSks);

            // 4. Masukkan teks ke dalam kotak yang bisa di-scroll
            javax.swing.JTextArea textArea = new javax.swing.JTextArea(detailText.toString());
            textArea.setEditable(false);
            textArea.setMargin(new java.awt.Insets(10, 10, 10, 10)); // Beri jarak tepi (padding)
            
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(450, 300)); // Ukuran pop-up

            // 5. Tampilkan ke layar dosen
            javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Detail Mata Kuliah", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            System.err.println("Gagal memuat detail: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem saat memuat detail KRS.");
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnValidasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidasiActionPerformed
        // TODO add your handling code here:
        int baris = tblKrsPending.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih mahasiswa di tabel terlebih dahulu!");
            return;
        }

        String idKrs = tblKrsPending.getValueAt(baris, 0).toString();
        String namaMhs = tblKrsPending.getValueAt(baris, 2).toString();

        Database db = new Database();
        try {
            // 1. Ambil detail KRS
            String sql = "SELECT kd.id_kelas, mk.kode_mk, mk.nama_mk, mk.sks, kd.status_detail " +
                         "FROM krs_detail kd JOIN kelas k ON kd.id_kelas = k.id_kelas " +
                         "JOIN mata_kuliah mk ON k.kode_mk = mk.kode_mk WHERE kd.id_krs = ?";
            java.sql.ResultSet rs = db.readDBSafe(sql, idKrs);

            // 2. Buat Tabel Virtual untuk Dialog Pilihan Dosen
            String[] kolom = {"ID Kelas", "Kode", "Mata Kuliah", "SKS", "Keputusan"};
            javax.swing.table.DefaultTableModel modelValidasi = new javax.swing.table.DefaultTableModel(kolom, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 4; // Hanya kolom "Keputusan" yang bisa diedit (diklik)
                }
            };

            int totalSks = 0;
            while (rs != null && rs.next()) {
                modelValidasi.addRow(new Object[]{
                    rs.getString("id_kelas"), rs.getString("kode_mk"), 
                    rs.getString("nama_mk"), rs.getString("sks"), "Setujui" // Default pilihan
                });
                totalSks += rs.getInt("sks");
            }

            javax.swing.JTable tblDialog = new javax.swing.JTable(modelValidasi);
            // Pasang ComboBox "Setujui/Tolak" ke kolom Keputusan
            javax.swing.JComboBox<String> cbKeputusan = new javax.swing.JComboBox<>(new String[]{"Setujui", "Tolak"});
            tblDialog.getColumnModel().getColumn(4).setCellEditor(new javax.swing.DefaultCellEditor(cbKeputusan));
            
            // 3. Susun UI Dialog
            javax.swing.JScrollPane scrollPanel = new javax.swing.JScrollPane(tblDialog);
            scrollPanel.setPreferredSize(new java.awt.Dimension(500, 200));
            javax.swing.JTextArea txtCatatan = new javax.swing.JTextArea(3, 20);
            
            javax.swing.JPanel panelDialog = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
            panelDialog.add(new javax.swing.JLabel("Validasi KRS: " + namaMhs + " (" + totalSks + " SKS) - Ubah kolom Keputusan:"), java.awt.BorderLayout.NORTH);
            panelDialog.add(scrollPanel, java.awt.BorderLayout.CENTER);
            
            javax.swing.JPanel panelCatatan = new javax.swing.JPanel(new java.awt.BorderLayout());
            panelCatatan.add(new javax.swing.JLabel("Catatan Validasi Dosen:"), java.awt.BorderLayout.NORTH);
            panelCatatan.add(new javax.swing.JScrollPane(txtCatatan), java.awt.BorderLayout.CENTER);
            panelDialog.add(panelCatatan, java.awt.BorderLayout.SOUTH);

            // 4. Tampilkan Dialog
int hasil = javax.swing.JOptionPane.showConfirmDialog(this, panelDialog, "Validasi KRS Parsial", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
            
            if (hasil == javax.swing.JOptionPane.OK_OPTION) {
                // FIX: Hentikan editing paksa agar nilai ComboBox terbaru tersimpan ke dalam tabel model
                if (tblDialog.isEditing()) {
                    tblDialog.getCellEditor().stopCellEditing();
                }

                // 5. Eksekusi Transaksi Database Berdasarkan Pilihan
                if (!db.beginTransaction()) return;
                
                int countSetuju = 0, countTolak = 0;
                int rowCount = tblDialog.getRowCount();
                
                for (int i = 0; i < rowCount; i++) {
                    String idKls = modelValidasi.getValueAt(i, 0).toString();
                    String keputusan = modelValidasi.getValueAt(i, 4).toString();
                    
                    if (keputusan.equals("Setujui")) {
                        db.executeDBSafe("UPDATE krs_detail SET status_detail = 'Disetujui' WHERE id_krs = ? AND id_kelas = ?", idKrs, idKls);
                        countSetuju++;
                    } else {
                        // Jika ditolak, set status dan KEMBALIKAN KUOTA kelas tersebut!
                        db.executeDBSafe("UPDATE krs_detail SET status_detail = 'Ditolak' WHERE id_krs = ? AND id_kelas = ?", idKrs, idKls);
                        db.executeDBSafe("UPDATE kelas SET kuota = kuota + 1 WHERE id_kelas = ?", idKls);
                        countTolak++;
                    }
                }
                
                // 6. Kalkulasi Status Header KRS
                String statusHeader = "Menunggu";
                if (countSetuju == rowCount) statusHeader = "Disetujui";
                else if (countTolak == rowCount) statusHeader = "Ditolak";
                else statusHeader = "Sebagian Ditolak";
                
                // Update header
                boolean ok = db.executeDBSafe("UPDATE krs_header SET status_validasi = ?, catatan_dosen = ? WHERE id_krs = ?", statusHeader, txtCatatan.getText(), idKrs);
                
                if (ok) {
                    db.commit();
                    javax.swing.JOptionPane.showMessageDialog(this, "Validasi berhasil disimpan dengan status: " + statusHeader);
                    tampilDataPending();
                } else {
                    db.rollback();
                }
            }
        } catch (Exception e) { System.err.println("Error Validasi Per MK: " + e.getMessage()); }
    
    }//GEN-LAST:event_btnValidasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSetuju;
    private javax.swing.JButton btnTolak;
    private javax.swing.JButton btnValidasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKrsPending;
    // End of variables declaration//GEN-END:variables
}
