/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelKelas extends javax.swing.JPanel {

    /**
     * Creates new form PanelKelas
     */
    public PanelKelas() {
        initComponents();
        
        // PANGGIL 2 FUNGSI INI DI SINI:
        loadComboBox(); // Untuk mengisi data Matkul dan Dosen
        tampilData();   // Untuk mengisi data Tabel di bawah
    }
// Variabel penampung ID Kelas saat baris tabel diklik
    private String idKelasTerpilih = "";

    private void loadComboBox() {
        try {
            Database db = new Database();
            // 1. Isi cbMatkul
            java.sql.ResultSet rsMk = (java.sql.ResultSet) db.readDB("kode_mk, nama_mk", "mata_kuliah", "1=1");
            cbMatkul.removeAllItems();
            while (rsMk != null && rsMk.next()) {
                cbMatkul.addItem(rsMk.getString("kode_mk") + " - " + rsMk.getString("nama_mk"));
            }

            // 2. Isi cbDosen
            java.sql.ResultSet rsDosen = (java.sql.ResultSet) db.readDB("nidn, nama_dosen", "dosen", "1=1");
            cbDosen.removeAllItems();
            while (rsDosen != null && rsDosen.next()) {
                cbDosen.addItem(rsDosen.getString("nidn") + " - " + rsDosen.getString("nama_dosen"));
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat pilihan: " + e.getMessage());
        }
    }

    private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Kelas");
        model.addColumn("Kode MK");
        model.addColumn("NIDN Dosen");
        model.addColumn("Ruang");
        model.addColumn("Hari");
        model.addColumn("Jam");
        model.addColumn("Kuota");
        tblKelas.setModel(model);

        try {
            Database db = new Database();
            java.sql.ResultSet rs = (java.sql.ResultSet) db.readDB("*", "kelas", "1=1");
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_kelas"),
                    rs.getString("kode_mk"),
                    rs.getString("nidn"),
                    rs.getString("ruang"),
                    rs.getString("hari"),
                    rs.getString("jam"),
                    rs.getString("kuota")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data kelas: " + e.getMessage());
        }
    }
    // FUNGSI KHUSUS UNTUK MEMBACA IRISAN WAKTU
    private boolean cekBentrokWaktu(String jamBaru, String jamAda) {
        try {
            // Bersihkan spasi dan ubah titik jadi pemisah jam:menit
            String jB = jamBaru.replace(" ", "").replace(".", ":");
            String jA = jamAda.replace(" ", "").replace(".", ":");
            
            // Konversi ke total menit agar gampang dihitung (misal 08:30 = 8*60 + 30 = 510)
            int start1 = (Integer.parseInt(jB.split("-")[0].split(":")[0]) * 60) + Integer.parseInt(jB.split("-")[0].split(":")[1]);
            int end1 = (Integer.parseInt(jB.split("-")[1].split(":")[0]) * 60) + Integer.parseInt(jB.split("-")[1].split(":")[1]);
            
            int start2 = (Integer.parseInt(jA.split("-")[0].split(":")[0]) * 60) + Integer.parseInt(jA.split("-")[0].split(":")[1]);
            int end2 = (Integer.parseInt(jA.split("-")[1].split(":")[0]) * 60) + Integer.parseInt(jA.split("-")[1].split(":")[1]);

            // Rumus irisan waktu: Mulai_1 lebih awal dari Selesai_2 DAN Mulai_2 lebih awal dari Selesai_1
            return start1 < end2 && start2 < end1;
        } catch (Exception e) {
            // Kalau admin ketiknya ngawur (ga pakai strip "-"), balik ke pengecekan teks biasa
            return jamBaru.equalsIgnoreCase(jamAda);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox<>();
        cbDosen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFilterMatkul = new javax.swing.JTextField();
        txtFilterDosen = new javax.swing.JTextField();
        txtRuang = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtKuota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbHari = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelas = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        jLabel1.setText("Kelola Kelas");

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Mata Kuliah");

        jLabel3.setText("Dosen");

        jLabel4.setText("Filter :");

        jLabel5.setText("Filter :");

        txtFilterMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterMatkulActionPerformed(evt);
            }
        });
        txtFilterMatkul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterMatkulKeyReleased(evt);
            }
        });

        txtFilterDosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilterDosenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterDosenKeyReleased(evt);
            }
        });

        txtRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuangActionPerformed(evt);
            }
        });

        jLabel6.setText("Ruangan");

        jLabel7.setText("Jam");

        jLabel8.setText("Kuota");

        jLabel9.setText("Hari");

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKelas);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilterMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilterDosen))
                            .addComponent(txtRuang)
                            .addComponent(txtJam)
                            .addComponent(txtKuota)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtFilterMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtFilterDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
if (cbMatkul.getSelectedItem() == null || cbDosen.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mata Kuliah atau Dosen belum dipilih!");
            return;
        }

        String kodeMk = cbMatkul.getSelectedItem().toString().split(" - ")[0];
        String nidn = cbDosen.getSelectedItem().toString().split(" - ")[0];
        String ruang = txtRuang.getText().trim(); // Sesuaikan nama variabel txtRuang/txtRuangan
        String jam = txtJam.getText().trim();
        String hari = cbHari.getSelectedItem().toString();
        String kuotaStr = txtKuota.getText().trim();

        if (ruang.isEmpty() || jam.isEmpty() || kuotaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua isian jadwal (Ruang, Jam, Kuota) harus diisi!");
            return;
        }
        // ==========================================================
        // SATPAM 0: CEK FORMAT JAM (ANTI-TYPO)
        if (!jam.matches("^\\d{2}[:.]\\d{2}\\s*-\\s*\\d{2}[:.]\\d{2}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Format Jam salah atau Typo!\n\nGunakan format standar 24 Jam.\nContoh yang benar: 08:00 - 10:30\natau 08.00-10.30");
            return;
        }
        // ==========================================================
        int kuota;
        try {
            kuota = Integer.parseInt(kuotaStr);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kolom Kuota harus berupa angka bulat!");
            return;
        }

        Database db = new Database();
        try {
            // SYARAT PENGECUALIAN SAAT UPDATE (Agar tidak bentrok dengan dirinya sendiri)
            String kecualiID = "";
            if (btnSimpan.getText().equals("Ubah Data")) {
                kecualiID = " AND id_kelas != '" + idKelasTerpilih + "'";
            }

            // SATPAM 1: CEK BENTROK RUANG (Update Logika Waktu)
            String cekRuang = "ruang = '" + ruang + "' AND hari = '" + hari + "'" + kecualiID;
            java.sql.ResultSet rsRuang = (java.sql.ResultSet) db.readDB("jam", "kelas", cekRuang);
            while (rsRuang != null && rsRuang.next()) {
                if (cekBentrokWaktu(jam, rsRuang.getString("jam"))) {
                    javax.swing.JOptionPane.showMessageDialog(this, "BENTROK! Ruang " + ruang + " sedang dipakai kelas lain pada jam " + rsRuang.getString("jam"));
                    return;
                }
            }

            // SATPAM 2: CEK BENTROK DOSEN (Update Logika Waktu)
            String cekDosen = "nidn = '" + nidn + "' AND hari = '" + hari + "'" + kecualiID;
            java.sql.ResultSet rsDosen = (java.sql.ResultSet) db.readDB("jam", "kelas", cekDosen);
            while (rsDosen != null && rsDosen.next()) {
                if (cekBentrokWaktu(jam, rsDosen.getString("jam"))) {
                    javax.swing.JOptionPane.showMessageDialog(this, "BENTROK! Dosen ini sudah mengajar kelas lain pada jam " + rsDosen.getString("jam"));
                    return;
                }
            }

            // EKSEKUSI DATABASE
            if (btnSimpan.getText().equals("Simpan")) {
                // LOGIKA SIMPAN BARU
                String kolom = "kode_mk, nidn, ruang, hari, jam, kuota";
                String nilai = "'" + kodeMk + "', '" + nidn + "', '" + ruang + "', '" + hari + "', '" + jam + "', '" + kuota + "'";
                if (db.createDB("kelas", kolom, nilai)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Jadwal Kelas Berhasil Dibuka!");
                    btnResetActionPerformed(evt);
                }
            } else {
                // LOGIKA UBAH DATA
                String nilaiUpdate = "kode_mk = '" + kodeMk + "', nidn = '" + nidn + "', ruang = '" + ruang + "', hari = '" + hari + "', jam = '" + jam + "', kuota = '" + kuota + "'";
                if (db.updateDB("kelas", nilaiUpdate, "id_kelas = '" + idKelasTerpilih + "'")) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Jadwal Kelas Berhasil Diperbarui!");
                    btnResetActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuangActionPerformed

    private void tblKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKelasMouseClicked
        // TODO add your handling code here:
        int baris = tblKelas.getSelectedRow();
        if (baris != -1) {
            idKelasTerpilih = tblKelas.getValueAt(baris, 0).toString();
            
            // Set teks biasa
            txtRuang.setText(tblKelas.getValueAt(baris, 3).toString());
            cbHari.setSelectedItem(tblKelas.getValueAt(baris, 4).toString());
            txtJam.setText(tblKelas.getValueAt(baris, 5).toString());
            txtKuota.setText(tblKelas.getValueAt(baris, 6).toString());
            
            // Set ComboBox Matkul
            String mkDicari = tblKelas.getValueAt(baris, 1).toString();
            for (int i = 0; i < cbMatkul.getItemCount(); i++) {
                if (cbMatkul.getItemAt(i).toString().startsWith(mkDicari + " -")) {
                    cbMatkul.setSelectedIndex(i); break;
                }
            }
            
            // Set ComboBox Dosen
            String dosenDicari = tblKelas.getValueAt(baris, 2).toString();
            for (int i = 0; i < cbDosen.getItemCount(); i++) {
                if (cbDosen.getItemAt(i).toString().startsWith(dosenDicari + " -")) {
                    cbDosen.setSelectedIndex(i); break;
                }
            }
            
            // Ubah tombol jadi "Ubah Data"
            btnSimpan.setText("Ubah Data");
        }
    }//GEN-LAST:event_tblKelasMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtRuang.setText("");
        txtJam.setText("");
        txtKuota.setText("");
        txtCari.setText("");
        txtFilterMatkul.setText("");
        txtFilterDosen.setText("");
        
        if (cbHari.getItemCount() > 0) cbHari.setSelectedIndex(0);
        idKelasTerpilih = "";
        
        loadComboBox();
        tampilData();
        tblKelas.clearSelection();
        btnSimpan.setText("Simpan");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idKelasTerpilih.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kelas di tabel yang ingin dihapus!");
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kelas/jadwal ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            if (db.deleteDB("kelas", "id_kelas = '" + idKelasTerpilih + "'")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Jadwal Kelas berhasil dihapus!");
                btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String kataKunci = txtCari.getText().trim();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblKelas.getModel();
        model.setRowCount(0); 
        try {
            Database db = new Database();
            String kondisi = "ruang LIKE '%" + kataKunci + "%' OR kode_mk LIKE '%" + kataKunci + "%' OR hari LIKE '%" + kataKunci + "%'";
            java.sql.ResultSet rs = (java.sql.ResultSet) db.readDB("*", "kelas", kondisi);
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{rs.getString("id_kelas"), rs.getString("kode_mk"), rs.getString("nidn"), rs.getString("ruang"), rs.getString("hari"), rs.getString("jam"), rs.getString("kuota")});
            }
            if (model.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Jadwal kelas tidak ditemukan!");
                tampilData();
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtFilterMatkulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterMatkulKeyReleased
        // TODO add your handling code here:
        String filter = txtFilterMatkul.getText().trim();
        try {
            Database db = new Database();
            java.sql.ResultSet rsMk = (java.sql.ResultSet) db.readDB("kode_mk, nama_mk", "mata_kuliah", "nama_mk LIKE '%" + filter + "%' OR kode_mk LIKE '%" + filter + "%'");
            cbMatkul.removeAllItems();
            while (rsMk != null && rsMk.next()) {
                cbMatkul.addItem(rsMk.getString("kode_mk") + " - " + rsMk.getString("nama_mk"));
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_txtFilterMatkulKeyReleased

    private void txtFilterDosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterDosenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterDosenKeyPressed

    private void txtFilterDosenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterDosenKeyReleased
        // TODO add your handling code here:
        String filter = txtFilterDosen.getText().trim();
        try {
            Database db = new Database();
            java.sql.ResultSet rsDosen = (java.sql.ResultSet) db.readDB("nidn, nama_dosen", "dosen", "nama_dosen LIKE '%" + filter + "%'");
            cbDosen.removeAllItems();
            while (rsDosen != null && rsDosen.next()) {
                cbDosen.addItem(rsDosen.getString("nidn") + " - " + rsDosen.getString("nama_dosen"));
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_txtFilterDosenKeyReleased

    private void txtFilterMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterMatkulActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKelas;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtFilterDosen;
    private javax.swing.JTextField txtFilterMatkul;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtKuota;
    private javax.swing.JTextField txtRuang;
    // End of variables declaration//GEN-END:variables
}
