/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;

/**
 *
 * @author User
 */
public class PanelPeriode extends javax.swing.JPanel {

    // Variabel penampung ID saat tabel diklik
    private String idPeriodeTerpilih = "";

    private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Periode"); model.addColumn("Tahun Ajaran");
        model.addColumn("Semester"); model.addColumn("Status KRS");
        tblPeriode.setModel(model);

        try {
            Database db = new Database();
            java.sql.ResultSet rs = db.readDBSafe("SELECT * FROM periode ORDER BY id_periode DESC");
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_periode"), rs.getString("tahun_ajaran"),
                    rs.getString("semester"), rs.getString("status_krs")
                });
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }
    /**
     * Creates new form PanelPeriode
     */
    public PanelPeriode() {
        initComponents();
        // --- TAMBAHKAN KODINGAN INI UNTUK MENGISI COMBOBOX ---
        cbSemester.removeAllItems();
        cbSemester.addItem("Ganjil");
        cbSemester.addItem("Genap");
        cbSemester.addItem("Pendek");
        
        cbStatus.removeAllItems();
        cbStatus.addItem("Buka");
        cbStatus.addItem("Tutup");
        // ----------------------------------------------------
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTahunAjaran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbSemester = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeriode = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jLabel1.setText("Tahun Ajaran");

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Semester");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buka", "Tutup" }));

        jLabel3.setText("Status");

        tblPeriode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPeriode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeriode);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbStatus, 0, 140, Short.MAX_VALUE)
                                    .addComponent(cbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTahunAjaran))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addContainerGap(166, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String tahun = txtTahunAjaran.getText().trim();
        String semester = cbSemester.getSelectedItem().toString();
        String status = cbStatus.getSelectedItem().toString();

        if (tahun.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tahun Ajaran tidak boleh kosong!");
            return;
        }

        Database db = new Database();
        try {
            // 1. MULAI TRANSAKSI
            if (!db.beginTransaction()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memulai transaksi database!");
                return;
            }

            // 2. TUTUP PERIODE LAMA JIKA PERIODE BARU DIBUKA
            if (status.equals("Buka")) {
                db.executeDBSafe("UPDATE periode SET status_krs = 'Tutup'"); 
            }

            boolean isSuccess = false;

            // 3. SIMPAN ATAU UBAH DATA PERIODE
            if (btnSimpan.getText().equals("Simpan")) {
                String sql = "INSERT INTO periode (tahun_ajaran, semester, status_krs) VALUES (?, ?, ?)";
                isSuccess = db.executeDBSafe(sql, tahun, semester, status);
            } else {
                String sql = "UPDATE periode SET tahun_ajaran = ?, semester = ?, status_krs = ? WHERE id_periode = ?";
                isSuccess = db.executeDBSafe(sql, tahun, semester, status, idPeriodeTerpilih);
            }

            // 4. JIKA SEMUA BERHASIL, SIMPAN PERMANEN (COMMIT)
            if (isSuccess) {
                db.commit();
                javax.swing.JOptionPane.showMessageDialog(this, 
                    btnSimpan.getText().equals("Simpan") ? "Periode Berhasil Ditambahkan!" : "Periode Berhasil Diperbarui!"
                );
                btnResetActionPerformed(evt);
            } else {
                // JIKA GAGAL INSERT/UPDATE, BATALKAN SEMUA TERMASUK UPDATE STATUS TUTUP
                db.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan periode. Data dibatalkan.");
            }
        } catch (Exception e) { 
            db.rollback(); // Jika terjadi error sistem, batalkan semua
            System.err.println("Terjadi Error: " + e.getMessage()); 
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi Error sistem, perubahan dibatalkan!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPeriodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodeMouseClicked
int baris = tblPeriode.getSelectedRow();
        if (baris != -1) {
            idPeriodeTerpilih = tblPeriode.getValueAt(baris, 0).toString();
            txtTahunAjaran.setText(tblPeriode.getValueAt(baris, 1).toString());
            cbSemester.setSelectedItem(tblPeriode.getValueAt(baris, 2).toString());
            cbStatus.setSelectedItem(tblPeriode.getValueAt(baris, 3).toString());
            
            btnSimpan.setText("Ubah Data");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblPeriodeMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idPeriodeTerpilih.isEmpty()) return;
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            if (db.executeDBSafe("DELETE FROM periode WHERE id_periode = ?", idPeriodeTerpilih)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Periode berhasil dihapus!");
                btnResetActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTahunAjaran.setText("");
        if (cbSemester.getItemCount() > 0) cbSemester.setSelectedIndex(0);
        if (cbStatus.getItemCount() > 0) cbStatus.setSelectedIndex(0);
        
        idPeriodeTerpilih = "";
        btnSimpan.setText("Simpan");
        tblPeriode.clearSelection();
        tampilData();
        txtTahunAjaran.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeriode;
    private javax.swing.JTextField txtTahunAjaran;
    // End of variables declaration//GEN-END:variables
}
