/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.krs;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author natha
 */
public class PanelMahasiswa extends javax.swing.JPanel {
private void loadComboBox() {
        try {
            Database db = new Database();
            // 1. Isi combobox Prodi (KUERI BARU AMAN)
            java.sql.ResultSet rsProdi = db.readDBSafe("SELECT id_prodi, nama_prodi FROM prodi");
            cbProdi.removeAllItems();
            while (rsProdi != null && rsProdi.next()) {
                cbProdi.addItem(rsProdi.getString("id_prodi") + " - " + rsProdi.getString("nama_prodi"));
            }

            // 2. Isi combobox Dosen Wali (KUERI BARU AMAN)
            java.sql.ResultSet rsDosen = db.readDBSafe("SELECT nidn, nama_dosen FROM dosen");
            cbDosenWali.removeAllItems();
            while (rsDosen != null && rsDosen.next()) {
                cbDosenWali.addItem(rsDosen.getString("nidn") + " - " + rsDosen.getString("nama_dosen"));
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat dropdown: " + e.getMessage());
        }
    }

    private void tampilData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Alamat");
        model.addColumn("Prodi");
        model.addColumn("Dosen Wali");
        model.addColumn("ID User");
        tblMahasiswa.setModel(model);

        try {
            Database db = new Database();
            // FITUR BARU: Double JOIN ke tabel prodi dan tabel dosen
            String sql = "SELECT m.nim, m.nama_mhs, m.alamat, m.id_prodi, p.nama_prodi, " +
                         "m.id_dosen_wali, d.nama_dosen, m.id_user " +
                         "FROM mahasiswa m " +
                         "LEFT JOIN prodi p ON m.id_prodi = p.id_prodi " +
                         "LEFT JOIN dosen d ON m.id_dosen_wali = d.nidn";
            java.sql.ResultSet rs = db.readDBSafe(sql);
            
            while (rs != null && rs.next()) {
                // Rangkai teks Prodi (misal: "1 - Sistem Informasi")
                String namaProdi = rs.getString("nama_prodi") != null ? rs.getString("nama_prodi") : "Tidak Ada/Dihapus";
                String prodiTampil = rs.getString("id_prodi") + " - " + namaProdi;
                
                // Rangkai teks Dosen Wali (misal: "12345 - Pak Budi")
                String namaDosen = rs.getString("nama_dosen") != null ? rs.getString("nama_dosen") : "Tidak Ada/Dihapus";
                String dosenTampil = rs.getString("id_dosen_wali") + " - " + namaDosen;

                model.addRow(new Object[]{
                    rs.getString("nim"),
                    rs.getString("nama_mhs"),
                    rs.getString("alamat"),
                    prodiTampil,  // <--- Masukkan teks prodi yang sudah dirangkai
                    dosenTampil,  // <--- Masukkan teks dosen yang sudah dirangkai
                    rs.getString("id_user")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * Creates new form PanelMahasiswa
     */
    public PanelMahasiswa() {
        initComponents();
        loadComboBox(); 
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNamaMhs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbDosenWali = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbProdi = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtFilterDosen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFilterProdi = new javax.swing.JTextField();

        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama Mahasiswa");

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama Mahasiswa", "Alamat", "Dosen Wali", "Pilih Prodi"
            }
        ));
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMahasiswa);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Alamat");

        jLabel7.setText("Dosen Wali");

        cbDosenWali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDosenWali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDosenWaliActionPerformed(evt);
            }
        });

        jLabel8.setText("Pilih Prodi");

        cbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtFilterDosen.setToolTipText("");
        txtFilterDosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterDosenKeyReleased(evt);
            }
        });

        jLabel5.setText("Filter :");

        jLabel9.setText("Filter :");

        txtFilterProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterProdiActionPerformed(evt);
            }
        });
        txtFilterProdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterProdiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbDosenWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFilterDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFilterProdi)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDosenWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFilterDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtFilterProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
// PROTEKSI AWAL: Mencegah NullPointerException jika dropdown kosong

if (cbProdi.getSelectedItem() == null || cbDosenWali.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Prodi atau Dosen Wali belum tersedia!");
            return;
        }

        String nim = txtNim.getText().trim();
        String nama = txtNamaMhs.getText().trim();
        String alamat = txtAlamat.getText().trim();
        String idProdi = cbProdi.getSelectedItem().toString().split(" - ")[0];
        String idDosen = cbDosenWali.getSelectedItem().toString().split(" - ")[0];

        if (nim.isEmpty() || nama.isEmpty() || alamat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
            return;
        }

        Database db = new Database();
        
        if (btnSimpan.getText().equals("Simpan")) {
            try {
                // Cek NIM duplikat
                java.sql.ResultSet rsCek = db.readDBSafe("SELECT username FROM admin WHERE username = ?", nim);
                if (rsCek != null && rsCek.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "NIM ini sudah memiliki akun!");
                    return;
                }

                // Insert ke tabel admin dan DAPATKAN id_admin-nya secara instan
                String sqlAdmin = "INSERT INTO admin (username, password) VALUES (?, ?)";
                int idBaru = db.insertAndGetId(sqlAdmin, nim, Database.hashPassword(nim));
                
                if (idBaru != -1) {
                    // Insert ke tabel mahasiswa menggunakan ID yang didapat
                    String sqlMhs = "INSERT INTO mahasiswa (nim, nama_mhs, alamat, id_prodi, id_dosen_wali, id_user) VALUES (?, ?, ?, ?, ?, ?)";
                    if (db.executeDBSafe(sqlMhs, nim, nama, alamat, idProdi, idDosen, idBaru)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Mahasiswa & Akun Otomatis Berhasil Dibuat!\nUsername: " + nim + "\nPassword: (Sama dengan NIM)");
                        tampilData();
                        btnResetActionPerformed(evt);
                    } else {
                        // ROLLBACK (Hapus akun jika gagal input mahasiswa)
                        db.executeDBSafe("DELETE FROM admin WHERE id_admin = ?", idBaru);
                        javax.swing.JOptionPane.showMessageDialog(this, "GAGAL menyimpan data ke tabel Mahasiswa!");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat akun login!");
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error Sistem: " + e.getMessage());
            }
        } else {
            // Mode Ubah
            if (tblMahasiswa.getSelectedRow() == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data mahasiswa di tabel dulu!"); 
                return;
            }

            String sqlUpdate = "UPDATE mahasiswa SET nama_mhs = ?, alamat = ?, id_prodi = ?, id_dosen_wali = ? WHERE nim = ?";
            if (db.executeDBSafe(sqlUpdate, nama, alamat, idProdi, idDosen, nim)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui!");
                tampilData(); 
                btnResetActionPerformed(evt); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
            }
        }

    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
      int baris = tblMahasiswa.getSelectedRow();
        if (baris != -1) {
            // Mengisi textfield dari kolom tabel
            txtNim.setText(tblMahasiswa.getValueAt(baris, 0).toString());
            txtNamaMhs.setText(tblMahasiswa.getValueAt(baris, 1).toString());
            txtAlamat.setText(tblMahasiswa.getValueAt(baris, 2).toString());
            
            // Mengunci NIM agar tidak bisa diedit saat proses Ubah
            txtNim.setEditable(false);
            
            // Sinkronisasi Dropdown Prodi (Sekarang sangat simpel)
            String prodiDariTabel = tblMahasiswa.getValueAt(baris, 3).toString();
            cbProdi.setSelectedItem(prodiDariTabel);
            
            // Sinkronisasi Dropdown Dosen Wali (Sangat simpel)
            String dosenDariTabel = tblMahasiswa.getValueAt(baris, 4).toString();
            cbDosenWali.setSelectedItem(dosenDariTabel);
        }
        btnSimpan.setText("Ubah Data");
    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
       int baris = tblMahasiswa.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus!");
            return;
        }

        String nim = txtNim.getText();
        Object idObj = tblMahasiswa.getValueAt(baris, 5);
        String idUser = (idObj != null) ? idObj.toString() : ""; 

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Menghapus Mahasiswa akan menghapus Akun Loginnya juga. Lanjutkan?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            Database db = new Database();
            
            // Hapus mahasiswa terlebih dahulu
            if (db.executeDBSafe("DELETE FROM mahasiswa WHERE nim = ?", nim)) {
                // Kemudian Hapus akun admin
                if (!idUser.isEmpty()) {
                    db.executeDBSafe("DELETE FROM admin WHERE id_admin = ?", idUser);
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Data Mahasiswa berhasil dihapus!");
                tampilData();
                btnResetActionPerformed(evt);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data Mahasiswa!");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // Mengosongkan kolom teks
        txtFilterProdi.setText(""); 
        txtFilterDosen.setText("");

        // Panggil ulang semua isinya
        loadComboBox();
        tampilData();
        btnSimpan.setText("Simpan");
        // Ganti tblMahasiswa dengan nama tabel di panel yang sedang kamu edit
        txtCari.setText("");
        tblMahasiswa.clearSelection();
        txtNim.setText("");
        txtNamaMhs.setText("");
        txtAlamat.setText("");
        
        // Mengembalikan dropdown ke pilihan pertama
        if (cbProdi.getItemCount() > 0) cbProdi.setSelectedIndex(0);
        if (cbDosenWali.getItemCount() > 0) cbDosenWali.setSelectedIndex(0);
        
        // Membuka kembali kunci NIM dan fokus ke kolom NIM
        txtNim.setEditable(true);
        txtNim.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbDosenWaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDosenWaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDosenWaliActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
       String kataKunci = "%" + txtCari.getText().trim() + "%";
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblMahasiswa.getModel();
        model.setRowCount(0);

        try {
            Database db = new Database();
            // Double JOIN yang sama untuk pencarian
            String sql = "SELECT m.nim, m.nama_mhs, m.alamat, m.id_prodi, p.nama_prodi, " +
                         "m.id_dosen_wali, d.nama_dosen, m.id_user " +
                         "FROM mahasiswa m " +
                         "LEFT JOIN prodi p ON m.id_prodi = p.id_prodi " +
                         "LEFT JOIN dosen d ON m.id_dosen_wali = d.nidn " +
                         "WHERE m.nim LIKE ? OR m.nama_mhs LIKE ?";
            java.sql.ResultSet rs = db.readDBSafe(sql, kataKunci, kataKunci);

            while (rs != null && rs.next()) {
                String namaProdi = rs.getString("nama_prodi") != null ? rs.getString("nama_prodi") : "Tidak Ada/Dihapus";
                String prodiTampil = rs.getString("id_prodi") + " - " + namaProdi;
                
                String namaDosen = rs.getString("nama_dosen") != null ? rs.getString("nama_dosen") : "Tidak Ada/Dihapus";
                String dosenTampil = rs.getString("id_dosen_wali") + " - " + namaDosen;

                model.addRow(new Object[]{
                    rs.getString("nim"), rs.getString("nama_mhs"), rs.getString("alamat"),
                    prodiTampil, dosenTampil, rs.getString("id_user")
                });
            }

            if (model.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                tampilData();
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtFilterDosenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterDosenKeyReleased
        // TODO add your handling code here:
        String filter = txtFilterDosen.getText().trim();
        try {
            Database db = new Database();
            java.sql.ResultSet rsDosen = db.readDBSafe("SELECT nidn, nama_dosen FROM dosen WHERE nama_dosen LIKE ?", "%" + filter + "%");
            cbDosenWali.removeAllItems();
            while (rsDosen != null && rsDosen.next()) {
                cbDosenWali.addItem(rsDosen.getString("nidn") + " - " + rsDosen.getString("nama_dosen"));
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }//GEN-LAST:event_txtFilterDosenKeyReleased

    private void txtFilterProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterProdiActionPerformed

    private void txtFilterProdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterProdiKeyReleased
       String filter = txtFilterProdi.getText().trim();
        try {
            Database db = new Database();
            java.sql.ResultSet rsProdi = db.readDBSafe("SELECT id_prodi, nama_prodi FROM prodi WHERE nama_prodi LIKE ?", "%" + filter + "%");
            cbProdi.removeAllItems();
            while (rsProdi != null && rsProdi.next()) {
                cbProdi.addItem(rsProdi.getString("id_prodi") + " - " + rsProdi.getString("nama_prodi"));
            }
        } catch (Exception e) { System.err.println("Terjadi Error: " + e.getMessage()); }
    }//GEN-LAST:event_txtFilterProdiKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosenWali;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtFilterDosen;
    private javax.swing.JTextField txtFilterProdi;
    private javax.swing.JTextField txtNamaMhs;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
